// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Apicurio) DeepCopyInto(out *Apicurio) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Apicurio.
func (in *Apicurio) DeepCopy() *Apicurio {
	if in == nil {
		return nil
	}
	out := new(Apicurio)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Apicurio) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApicurioAuthRresource) DeepCopyInto(out *ApicurioAuthRresource) {
	*out = *in
	out.ApicurioResource = in.ApicurioResource
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApicurioAuthRresource.
func (in *ApicurioAuthRresource) DeepCopy() *ApicurioAuthRresource {
	if in == nil {
		return nil
	}
	out := new(ApicurioAuthRresource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApicurioList) DeepCopyInto(out *ApicurioList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Apicurio, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApicurioList.
func (in *ApicurioList) DeepCopy() *ApicurioList {
	if in == nil {
		return nil
	}
	out := new(ApicurioList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ApicurioList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApicurioResource) DeepCopyInto(out *ApicurioResource) {
	*out = *in
	out.Memory = in.Memory
	out.CPU = in.CPU
	out.JVM = in.JVM
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApicurioResource.
func (in *ApicurioResource) DeepCopy() *ApicurioResource {
	if in == nil {
		return nil
	}
	out := new(ApicurioResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApicurioSpec) DeepCopyInto(out *ApicurioSpec) {
	*out = *in
	out.Auth = in.Auth
	out.Api = in.Api
	out.WebSocket = in.WebSocket
	out.Studio = in.Studio
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApicurioSpec.
func (in *ApicurioSpec) DeepCopy() *ApicurioSpec {
	if in == nil {
		return nil
	}
	out := new(ApicurioSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApicurioStatus) DeepCopyInto(out *ApicurioStatus) {
	*out = *in
	if in.Reason != nil {
		in, out := &in.Reason, &out.Reason
		*out = new(string)
		**out = **in
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApicurioStatus.
func (in *ApicurioStatus) DeepCopy() *ApicurioStatus {
	if in == nil {
		return nil
	}
	out := new(ApicurioStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinMaxCfg) DeepCopyInto(out *MinMaxCfg) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinMaxCfg.
func (in *MinMaxCfg) DeepCopy() *MinMaxCfg {
	if in == nil {
		return nil
	}
	out := new(MinMaxCfg)
	in.DeepCopyInto(out)
	return out
}
